# Generated by Django 5.2.6 on 2025-09-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
